### ISSUE TITLE
Cache LFS files in usages of `actions/checkout`

### ISSUE THREAD

**Issue by jakob-ed** [bakdata/ci-templates#126]
GitHub has a minimal free quota for LFS https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage

It seems that `actions/checkout` does not cache LFS files between workflow runs in a repo when the action is used with `lfs: true` so that the quota is affected by every run: https://github.com/actions/checkout/issues/165

Consider using https://github.com/nschloe/action-cached-lfs-checkout which is able to cache LFS files.

**Comment by yannick-roeder** [comment]
## Edge cases and ideal behaviour

1. File gets deleted -> Delete file also gets deleted from cache
2. File gets added -> Newly added file gets pulled from repo and added to cache
3. File name changes -> Renamed file does not need to be pulled from repo again and gets renamed in cache
4. Data in file changes -> File with changed contents gets pulled from repo and added to the cache

**Comment by MichaelKora** [comment]
the gihtub action [cache](https://github.com/actions/cache) support caching
