### ISSUE TITLE
Replace docker-build action in all workflows with official action

### ISSUE THREAD

**Issue by yannick-roeder** [bakdata/ci-templates#139]
## Description

Initially we decided against the official [docker-build-push action](https://github.com/docker/build-push-action) since it didn't seem to support building without pushing. Now there is an input `push` which can be set to false, so we can use this action for building and still rely on our [custom tagging logic](https://github.com/bakdata/ci-templates/blob/main/actions/docker-push/action.yaml#L43-L50) for pushing images build from Dockerfiles and Jib. We want to remove our docker-build action and replace it in every workflow with the [docker-build-push action](https://github.com/docker/build-push-action), because it offers more features.

## Acceptance criteria

- [ ] The `docker-build` action should be removed
- [ ] The docker-build and publish action should be used in every workflow

**Comment by jakob-ed** [comment]
Regarding tagging, there is also https://github.com/docker/metadata-action whose `type=raw,value=` seems to be quite flexible. Perhaps it's possible to do `type=raw,value=pipeline-${{ github.run_id }}-git-{{sha}}`?
