### ISSUE TITLE
Increase the timeout when publishing via poetry

### ISSUE THREAD

**Issue by sujuka99** [bakdata/ci-templates#162]
The CI in KPOps has been [failing](https://github.com/bakdata/kpops/actions/runs/7131141935/job/19419208165) quite often lately during publishing to test pypi. 

[Related](https://github.com/python-poetry/poetry/pull/7081/files)

**Comment by yannick-roeder** [comment]
Fixed by https://github.com/bakdata/ci-templates/pull/172
