### ISSUE TITLE
Prevent the auto-doc pre-commit from being run multiple times before merging

### ISSUE THREAD

**Issue by MichaelKora** [bakdata/ci-templates#164]
Right now, when a documentation file is outdated, the `pre-commit`  / `git commit` command need to be executed at least three time:
1. Update the file
2. Format the file
3. Run an successful execution

It would be ideal if the command can be just executed once and all of those steps will be at once if needed.

## Acceptance Criteria

- [ ] When a file is outdated, the `git-commit` needs to be run just once.
- [ ] Up to date files will not be changed.
- [ ] Both `pre-commit run --all-files` and `git commit -m"xxxx"` have the exact same behaviour.

**Comment by yannick-roeder** [comment]
Executing it multiple times is the expected behaviour by the pre-commit and there is no parameter to configure this further
