### ISSUE TITLE
Node.js 16 deprecated 

### ISSUE THREAD

**Issue by raminqaf** [bakdata/ci-templates#174]
After running the release workflow, I encountered this message:
```
Node.js 16 actions are deprecated. 
Please update the following actions to use Node.js 20: 
actions/checkout@v3, ad-m/github-push-action@v0.6.0, softprops/action-gh-release@v1. 
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
We should consider to update all of our workflows.

**Comment by yannick-roeder** [comment]
Here is a workflow where the message is visible as well:
https://github.com/bakdata/k8s-application-deployment/actions/runs/8734737189
