### ISSUE TITLE
Create action for deploying and updating mkdocs with `mike`

### ISSUE THREAD

**Issue by raminqaf** [bakdata/ci-templates#75]
It would be nice to have an action that deploys and updates the mkdocs using the CLI tool [mike](https://github.com/jimporter/mike).
We use two identical actions in our repositories, which can be replaced by ci-templates:

- [KPOPs](https://github.com/bakdata/kpops/blob/main/.github/actions/update-docs/action.yml)
- [Quick](https://github.com/bakdata/quick/blob/master/.github/actions/update-docs/action.yml)

**Comment by yannick-roeder** [comment]
Not relevant anymore, since it is not used that much anymore
